### ISSUE TITLE
Slime Duplication Glitch + Immortality

### ISSUE THREAD

**Issue by LilGitty** [Ethanol10/rimuru-tempest-ror2#10]
Hey again,
Today I played multiplayer and had a very very weird run.

1. The infinite item glitch is still present. But now we have some evidence it might be linked to switching characters and the game thinking you are no longer Rimuru but ??? (See images:1+2
![image1](https://github.com/Ethanol10/rimuru-tempest-ror2/assets/102741460/720446fc-6623-45c5-b619-09c81dc46b8b)
![image2](https://github.com/Ethanol10/rimuru-tempest-ror2/assets/102741460/2048b813-eafc-4564-af0c-cc0c8d85eb67)
)

2. Immortality - My friend switched forms and somehow created a clone Rimuru which holds his HP (140 constant).
If he gets damaged on his real form, then the damage returns to 140.
If the blow taken is too high, he "dies" but resurrects instantly.
(See Images: 3+4+5
![image3](https://github.com/Ethanol10/rimuru-tempest-ror2/assets/102741460/ee82aaa6-f361-4484-b782-ec59e49c5ae0)
![image4](https://github.com/Ethanol10/rimuru-tempest-ror2/assets/102741460/3ba8dde9-38dc-4752-b313-84411b7fb609)
)
In This scenario, the duplicated Rimuru is inside the mountains (Image 5)
![image5](https://github.com/Ethanol10/rimuru-tempest-ror2/assets/102741460/eede199a-87e8-44ed-b27c-042187d555e9)
![image6](https://github.com/Ethanol10/rimuru-tempest-ror2/assets/102741460/07690e6d-beb9-495d-a293-085625ed91ba)

Of course after the teleporter the duplicate disappears.

3. You can hit yourself with icicle strike if you jump and transform and let it hit you midair.
4. Evidence for ???:
When you switch forms, the chat log jumps back and forth. Idk if this is related.

I added the log as well, this also serves as log for the infinite item glitch if it helps.

Good luck, and hope the mod will be fixed soon!
[LogOutput.log](https://github.com/Ethanol10/rimuru-tempest-ror2/files/13539948/LogOutput.log)

**Comment by Ethanol10** [comment]
This might be tied into the body transform code, I tried to fix it in 1.0.4, hope this will be ok?
I'll keep the ticket open in case.

**Comment by LilGitty** [comment]
Hey again,
We tested it again and it seems to be working fine!
We had one bug that we couldn't recreate where you spectate yourself when spawning into the next stage and spamming transformation or something but it might have been random.

Anyways it has been a journey, congrats on finally fixing it!
