### ISSUE TITLE
Slime form doesn't land on sword on Simulacrum Lobby.

### ISSUE THREAD

**Issue by SlawekNowy** [Ethanol10/rimuru-tempest-ror2#12]
![20240503152435_1](https://github.com/Ethanol10/rimuru-tempest-ror2/assets/38943477/79d53c16-f8bb-49d9-b7e5-21bb55828e51)

**Comment by Ethanol10** [comment]
huh, strange bug, i'll look into it when I have the time.

**Comment by Ethanol10** [comment]
Seems like a weird bug I can't fix sorry. I will close the issue as won't fix, as it does not hamper gameplay.
