### ISSUE TITLE
Should Devour and Human M2 be interrupted, their effect will still linger on world.

### ISSUE THREAD

**Issue by SlawekNowy** [Ethanol10/rimuru-tempest-ror2#14]
By interruption I mean, form swap or death. It will be present until game reset.

**Comment by SlawekNowy** [comment]
Both visual effect and the sound. Thankfully not its hitbox (confirm this).

**Comment by Ethanol10** [comment]
Can't seem to reproduce this issue, was this online with you as the client or the server?

**Comment by SlawekNowy** [comment]
I was playing solo, however I had about 40FPS...

**Comment by Ethanol10** [comment]
Hrm, I tried dying while using the move for both m2 and devour, neither lingered on death or on transform

**Comment by SlawekNowy** [comment]
Might be a mod collision...? I'll re-run and send you the log.

**Comment by SlawekNowy** [comment]
Can't recreate it. Closing.
