### ISSUE TITLE
Infinite Item Glitch

### ISSUE THREAD

**Issue by Znachary** [Ethanol10/rimuru-tempest-ror2#7]
Cannot collect items, but rather they take up your inventory and you end up collecting hundreds of the same item

**Comment by Ethanol10** [comment]
Hi, was there anything particulary unique when you were picking up items?

E.g, changing between forms, specific mods affecting items, only happens on rimuru etc.

**Comment by Znachary** [comment]
Nothing external changed when picking up items, although i didn't see if there was a difference when picking up items in slime form vs human form. This bug only happened with Rimuru as my friends didn't have this issue, although one of them couldn't pick items so that may be relevant. The following is a list of all the other mods I have downloaded (excluding their dependencies) in case any of those are creating the issue.
-EmptyChestsBeGone
-Goku/Vegeta/Trunks
-KingItems
-SkipIntro
-Starstorm2

**Comment by Ethanol10** [comment]
Hi, Thanks for the bug report! I'll have a look into it soon.

**Comment by Hlebuw3k** [comment]
This is still an issue. My friend wont let me play this character because it just breaks the game and lets me pick up infinite items, standing on an item gives 1 of it every frame instead of picking it up.

**Comment by Ethanol10** [comment]
Yes, I'm aware. I'm not sure if I can fix this issue entirely to be honest, tried a bunch of things to no avail.

**Comment by Ethanol10** [comment]
Hi there, should be fixed in v1.0.4!
