### ISSUE TITLE
Weird Infinite Items Glitch

### ISSUE THREAD

**Issue by LilGitty** [Ethanol10/rimuru-tempest-ror2#8]
Hey, just wanna let you know on a glitch i discovered on a playthrough:
**The moment you transform once into a slime**, the game is bugged and you can pick items infinitely without them disappearing off the ground.
This results in enemies dying but their models remain still, and some projectiles stuck in the air.
This also makes the game run much worse.

Great mod btw, waiting for a new update, cheers.

**Comment by Ethanol10** [comment]
Hi there, do you have a log?

**Comment by Ethanol10** [comment]
Also, is this multiplayer or singleplayer

**Comment by LilGitty** [comment]
Only works in multiplayer.
Log sent in new Issue.

**Comment by Ethanol10** [comment]
Thanks for the bug report! I'll have a look into it soon!

**Comment by Ethanol10** [comment]
Hi there, this should be fixed in v1.0.4
