### ISSUE TITLE
Necessary Mod Isn't Included in Required Mods List

### ISSUE THREAD

**Issue by LilGitty** [Ethanol10/rimuru-tempest-ror2#9]
Hey,
When you just download the Rimuru mod and launch it, it doesn't actually load Rimuru.
After some trial and error with Goku Mod we discovered that a certain mod: "R2API_Unlockable" Is required in order to play as Rimuru, but it isn't in the required mods in the download.

Keep up the good work!

**Comment by Ethanol10** [comment]
Thanks for that, I'll get it removed, was an accident from the get go!
